"""server.properties / eula.txt / whitelist.json generation and Paper config
patching.

First-boot bootstrap: we briefly launch the server so Paper writes its own
default config files (config/paper-global.yml, paper-world-defaults.yml,
bukkit.yml, spigot.yml), then stop it cleanly. We only do this to get a
real, version-correct config skeleton to patch - much safer than hand
authoring a full paper-global.yml from scratch, since its schema shifts
between Minecraft versions.

The wizard's gameplay answers are a single dict with fixed keys (tnt_dupe,
block_break_exploits, headless_pistons, anti_xray, anti_xray_mode,
allow_end). UNSUPPORTED_SETTINGS is the one place that maps those answers
to their YAML keys; both the auto-patcher below and
write_manual_config_notes() (the no-Java fallback) read from it so the two
can never drift apart. allow-end has no Paper setting - it lives in
bukkit.yml, which the bootstrap generates alongside the Paper configs.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import signal
import subprocess
import threading
import time
import uuid
from pathlib import Path

import yaml

from .ui import error, info, ok, warn

# Forward-slash names (used both for joining onto the server dir and for
# display in MANUAL_CONFIG_NOTES.txt, which should look the same on Windows
# and Unix).
PAPER_GLOBAL_CONFIG = "config/paper-global.yml"
PAPER_WORLD_DEFAULTS = "config/paper-world-defaults.yml"
PAPER_LEGACY_CONFIG = "paper.yml"
BUKKIT_CONFIG = "bukkit.yml"

# (wizard answer key, paper yaml key) - single source of truth for the three
# toggles patched under "unsupported-settings".
UNSUPPORTED_SETTINGS = (
    ("tnt_dupe", "allow-piston-duplication"),
    ("block_break_exploits", "allow-permanent-block-break-exploits"),
    ("headless_pistons", "allow-headless-pistons"),
)

DEFAULT_PROPERTIES = {
    "accepts-transfers": "false",
    "allow-flight": "false",
    "allow-nether": "true",
    "broadcast-console-to-ops": "true",
    "broadcast-rcon-to-ops": "true",
    "difficulty": "easy",
    "enable-command-block": "false",
    "enable-jmx-monitoring": "false",
    "enable-query": "false",
    "enable-rcon": "false",
    "enable-status": "true",
    "enforce-secure-profile": "true",
    "enforce-whitelist": "false",
    "entity-broadcast-range-percentage": "100",
    "force-gamemode": "false",
    "function-permission-level": "2",
    "gamemode": "survival",
    "generate-structures": "true",
    "generator-settings": "{}",
    "hardcore": "false",
    "hide-online-players": "false",
    "initial-disabled-packs": "",
    "initial-enabled-packs": "vanilla",
    "level-name": "world",
    "level-seed": "",
    "level-type": "minecraft\\:normal",
    "log-ips": "true",
    "max-chained-neighbor-updates": "1000000",
    "max-players": "20",
    "max-tick-time": "60000",
    "max-world-size": "29999984",
    "motd": "A Minecraft Server",
    "network-compression-threshold": "256",
    "online-mode": "true",
    "op-permission-level": "4",
    "player-idle-timeout": "0",
    "prevent-proxy-connections": "false",
    "pvp": "true",
    "query.port": "25565",
    "rate-limit": "0",
    "rcon.password": "",
    "rcon.port": "25575",
    "region-file-compression": "deflate",
    "require-resource-pack": "false",
    "resource-pack": "",
    "resource-pack-id": "",
    "resource-pack-prompt": "",
    "resource-pack-sha1": "",
    "server-ip": "",
    "server-port": "25565",
    "simulation-distance": "10",
    "spawn-protection": "16",
    "sync-chunk-writes": "true",
    "text-filtering-config": "",
    "use-native-transport": "true",
    "view-distance": "10",
    "white-list": "false",
}


def _yn(value: bool) -> str:
    return "true" if value else "false"


def _property_value(value) -> str:
    """server.properties values are strings; accept raw bools/ints from the
    wizard and serialize them here so callers don't repeat conversions."""
    if isinstance(value, bool):
        return _yn(value)
    return str(value)


def write_eula(server_dir: Path) -> None:
    (server_dir / "eula.txt").write_text(
        "#By changing the setting below to TRUE you are indicating your agreement "
        "to our EULA (https://aka.ms/MinecraftEULA).\neula=true\n",
        encoding="utf-8",
    )


def write_server_properties(server_dir: Path, overrides: dict) -> None:
    props = dict(DEFAULT_PROPERTIES)
    props.update({key: _property_value(value) for key, value in overrides.items()})
    lines = ["#Minecraft server properties", "#Generated by Blizzards Server Installer"]
    for key in sorted(props):
        lines.append(f"{key}={props[key]}")
    (server_dir / "server.properties").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _kill_process_tree(pid: int) -> None:
    """Force-kill a process and everything it spawned.

    A Java launcher can keep the actual JVM running as a child process, so
    killing only the tracked PID can leave a server behind holding the
    folder open. On Windows taskkill /T removes the whole tree; on POSIX
    the server was started in its own session (start_new_session) so we
    signal the entire process group."""
    if os.name == "nt":
        subprocess.run(
            ["taskkill", "/PID", str(pid), "/T", "/F"],
            capture_output=True,
        )
    else:
        try:
            # signal.SIGKILL doesn't exist on Windows' signal module, but
            # this branch only runs on POSIX; 9 is SIGKILL there.
            os.killpg(os.getpgid(pid), getattr(signal, "SIGKILL", 9))
        except (ProcessLookupError, PermissionError):
            pass


def _stop_server(proc) -> None:
    """Shut the bootstrapped server down, escalating until it is really gone.

    First the in-game "stop" command with a generous grace period (lets the
    server save worlds cleanly). If that times out, force-kill the whole
    process tree rather than just the tracked PID - terminating only the
    launcher can orphan the JVM child on Windows, which is exactly what left
    a server running after earlier installs."""
    if proc.poll() is not None:
        return
    try:
        proc.stdin.write("stop\n")
        proc.stdin.flush()
    except Exception:
        pass
    try:
        proc.wait(timeout=60)
        return
    except subprocess.TimeoutExpired:
        warn("Server didn't stop gracefully in time, terminating it.")
    _kill_process_tree(proc.pid)
    try:
        proc.wait(timeout=15)
    except subprocess.TimeoutExpired:
        warn("Could not fully stop the server - it may still be running in the background.")


def bootstrap_configs(server_dir: Path, jar_path: Path, timeout: int = 180) -> bool:
    java = shutil.which("java")
    if not java:
        warn("No Java installation found on PATH - skipping automatic config generation.")
        return False

    info("Starting the server once to generate default config files (up to a few minutes)...")
    try:
        proc = subprocess.Popen(
            [java, "-Xms512M", "-Xmx1024M", "-jar", jar_path.name, "--nogui"],
            cwd=str(server_dir),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            # Own session/process group so _kill_process_tree() can signal
            # the whole tree instead of only this tracked PID.
            start_new_session=True,
        )
    except Exception as exc:
        warn(f"Could not launch Java to bootstrap configs ({exc}).")
        return False

    def _drain():
        try:
            for _ in iter(proc.stdout.readline, ""):
                pass
        except Exception:
            pass

    threading.Thread(target=_drain, daemon=True).start()

    target = server_dir / PAPER_GLOBAL_CONFIG
    legacy_target = server_dir / PAPER_LEGACY_CONFIG
    start = time.time()
    generated = False
    while time.time() - start < timeout:
        if target.exists() or legacy_target.exists():
            time.sleep(3)  # let the rest of the config batch finish writing
            generated = True
            break
        if proc.poll() is not None:
            break
        time.sleep(1)

    _stop_server(proc)

    if generated:
        ok("Default config files generated.")
    else:
        warn("Timed out waiting for config files to appear.")
    return generated


def find_paper_config_paths(server_dir: Path):
    """Returns (global_config_path, world_defaults_path_or_None, is_legacy)."""
    modern_global = server_dir / PAPER_GLOBAL_CONFIG
    modern_world = server_dir / PAPER_WORLD_DEFAULTS
    legacy = server_dir / PAPER_LEGACY_CONFIG
    if modern_global.exists():
        return modern_global, (modern_world if modern_world.exists() else None), False
    if legacy.exists():
        return legacy, legacy, True
    return None, None, False


def patch_yaml(path: Path, patch_fn) -> None:
    """Load a YAML file, run patch_fn on its data, and write it back.

    Uses PyYAML's safe loader/dumper: comments in Paper's generated files are
    not preserved (cosmetic only - Paper regenerates/ignores them), but the
    key order and every value the server actually reads are kept intact.
    """
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if data is None:
        return
    patch_fn(data)
    with open(path, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False, default_flow_style=False, allow_unicode=True)


def _nested(data: dict, *keys: str) -> dict:
    """Walk (creating as needed) a chain of nested dict keys and return the leaf."""
    node = data
    for key in keys:
        node = node.setdefault(key, {})
    return node


def set_unsupported_settings(data: dict, answers: dict) -> None:
    us = _nested(data, "unsupported-settings")
    for answer_key, yaml_key in UNSUPPORTED_SETTINGS:
        us[yaml_key] = answers[answer_key]


def set_allow_end(data: dict, enabled: bool) -> None:
    """bukkit.yml's allow-end toggle (nested under settings:, exactly where
    Paper's generated file puts it) - the only stock way to disable the End,
    since server.properties has no allow-end key."""
    _nested(data, "settings")["allow-end"] = enabled


def set_anti_xray(data: dict, enabled: bool, engine_mode: int) -> None:
    # Modern layout: anticheat.anti-xray.*  Legacy layout: world-settings.default.anti-xray.*
    if "world-settings" in data and "anticheat" not in data:
        ax = _nested(data, "world-settings", "default", "anti-xray")
    else:
        ax = _nested(data, "anticheat", "anti-xray")
    ax["enabled"] = enabled
    if enabled:
        ax["engine-mode"] = engine_mode


def apply_gameplay_config(server_dir: Path, jar_path: Path, answers: dict) -> None:
    generated = bootstrap_configs(server_dir, jar_path)
    if not generated:
        write_manual_config_notes(server_dir, answers)
        warn("Couldn't auto-generate Paper's config - see MANUAL_CONFIG_NOTES.txt for what to change by hand.")
        return

    global_path, world_path, _legacy = find_paper_config_paths(server_dir)
    if global_path:
        try:
            patch_yaml(global_path, lambda d: set_unsupported_settings(d, answers))
            ok(f"Patched {global_path.relative_to(server_dir)}")
        except Exception as exc:
            error(f"Failed to patch {global_path.name}: {exc}")

    target_world = world_path or global_path
    if target_world:
        try:
            patch_yaml(target_world, lambda d: set_anti_xray(d, answers["anti_xray"], answers["anti_xray_mode"]))
            ok(f"Patched {target_world.relative_to(server_dir)} (anti-xray)")
        except Exception as exc:
            error(f"Failed to patch anti-xray settings: {exc}")

    bukkit_path = server_dir / BUKKIT_CONFIG
    if bukkit_path.exists():
        try:
            patch_yaml(bukkit_path, lambda d: set_allow_end(d, answers.get("allow_end", True)))
            ok(f"Patched {BUKKIT_CONFIG} (allow-end)")
        except Exception as exc:
            error(f"Failed to patch allow-end in {BUKKIT_CONFIG}: {exc}")


def write_manual_config_notes(server_dir: Path, answers: dict) -> None:
    unsupported_lines = "\n".join(
        f"    {yaml_key}: {_yn(answers[answer_key])}"
        for answer_key, yaml_key in UNSUPPORTED_SETTINGS
    )
    notes = f"""Blizzards Server Installer - manual config notes
==============================================

Java wasn't found on this machine, so the installer couldn't launch the
server once to generate Paper's default config files and patch them for
you. Install a Java 21+ runtime (https://adoptium.net), start the server
once with start.bat / start.sh, stop it again, then edit the following
files by hand:

{PAPER_GLOBAL_CONFIG}, under "unsupported-settings":
{unsupported_lines}

{PAPER_WORLD_DEFAULTS}, under "anticheat" -> "anti-xray":
    enabled: {_yn(answers['anti_xray'])}
    engine-mode: {answers['anti_xray_mode']}

{BUKKIT_CONFIG}, under "settings":
    allow-end: {_yn(answers.get('allow_end', True))}

(On Paper versions older than 1.19 these settings live in a single root
paper.yml file instead of the config/ folder.)
"""
    (server_dir / "MANUAL_CONFIG_NOTES.txt").write_text(notes, encoding="utf-8")


def offline_player_uuid(name: str) -> str:
    """The UUID Java assigns to a player on offline-mode servers.

    Offline profiles are GameProfile(uuid = nameUUIDFromBytes("OfflinePlayer:"
    + name)) - a UUID v3 (MD5) with the version/variant bits set. Writing the
    exact same UUID into whitelist.json makes the entry match the joining
    player, which vanilla's own `whitelist add` gets wrong on offline servers.
    """
    digest = bytearray(hashlib.md5(f"OfflinePlayer:{name}".encode("utf-8")).digest())
    digest[6] = (digest[6] & 0x0F) | 0x30  # UUID version 3
    digest[8] = (digest[8] & 0x3F) | 0x80  # RFC 4122 variant
    return str(uuid.UUID(bytes=bytes(digest)))


def write_whitelist(server_dir: Path, entries: list[dict]) -> None:
    """Write whitelist.json (vanilla whitelist file).

    Entries are {"uuid", "name"} dicts in the same shape the server's own
    `whitelist add` command produces. A blank/missing uuid would never match
    a joining player, so callers must resolve real UUIDs first (Mojang API in
    online mode, offline_player_uuid() otherwise)."""
    path = server_dir / "whitelist.json"
    path.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
